### ISSUE TITLE
How to delete logs in Security Log tab?

### ISSUE THREAD

**Issue by MythodeaLoL** [EFTEC/Cyberarms#10]
Hello, I would like to know how I can delete the logs from the Security Log tab, over time will accommodate thousands of logs, and I would like a button or know how to delete the logs.

Thank you for this fantastic program, you're the guy. @jorgecc @ProfessorJoe

**Comment by maxemilian** [comment]
Hi there

 

We do not have a data cleanup at the moment. The only way is to unlock the current locks and delete the database file found in your Cyberarms application directory. Please be aware you will have to reconfigure the product after removing the database file. 

 

Optionally you can wait for version 3.0 which will cover database cleanup and other cool features 😉

 

Best regards

 

Max

 

Maxemilian Hilbrand (Software & Systeme)




CH: +41 71 511 722 0
AT (mobile): +43 660 703 92 54
 <mailto:maxemilian.hilbrand@isicore.com> maxemilian.hilbrand@isicore.com


isicore AG • Unterlettenstrasse 14 • CH-9443 Widnau
Gerichtsstandort CH-9450 Altstätten, UID CHE-110.354.078
Verwaltungsratspräsident: Maxemilian Hilbrand

 <http://www.isicore.com/> www.isicore.com I   <mailto:info@isicore.com> info@isicore.com

 

Von: FloridaStream <notifications@github.com> 
Gesendet: Samstag, 19. Oktober 2019 01:02
An: EFTEC/Cyberarms <Cyberarms@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [EFTEC/Cyberarms] How to delete logs in Security Log tab? (#10)

 

Hello, I would like to know how I can delete the logs from the Security Log tab, over time will accommodate thousands of logs, and I would like a button or know how to delete the logs.

Thank you for this fantastic program, you're the guy. @jorgecc <https://github.com/jorgecc>  @ProfessorJoe <https://github.com/ProfessorJoe>

**Comment by MythodeaLoL** [comment]
Understand. I can't wait for version 3, this program helped me tremendously.

If you can, check to make sure if you make a mistake 4 times after a few days, once again making a mistake, IDDS is not blacklisting the IP. 
Apparently I think so, but I didn't find the IP, just putting my IP on whitelist I was able to remove my block. I just missed 4 out of 5, it may have been a bug, I don't know, but it gets the alert for v3. 

See you later.
