### ISSUE TITLE
Error installing on Win 10 Pro - setup has detected vcredist_x64.exe has changed since it was initially published

### ISSUE THREAD

**Issue by aero-knight** [EFTEC/Cyberarms#16]
Hi, I am trying to install Cyberarms Intrusion Detection on my Win 10 Pro machine. 

I am getting the error during the Visual C++ install that setup has detected vcredist_x64.exe has changed since it was initially published. 

![Screenshot 2022-02-23 094246](https://user-images.githubusercontent.com/100258814/155267392-1a535e11-5020-4628-859a-9ef7ab8e3553.png)

Any guidance you can provide will be appreciated. Thanks in advance.

**Comment by Catsrules** [comment]
Sounds like the same issue at case #14 
You just need to download the Visual C++ manually. I believe it is 2010

**Comment by aero-knight** [comment]
Thanks @Catsrules - this works.

For others who have this problem:
1. Download Visual C++ manually from here: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
2. You only need to install 2010 - do not run the batch file, ignore the other installers. 
3. Run Cyberarms.IntrusionDetection.Setup.x64.msi (if you run setup.exe, it will try and auto install vcredist_x64 and fail).
